title: Adirondack Bank Status Page
languageCode: en
params:
  shortDateFormat: 15:04 — Jan 2
  meta_description: This status page provides updated information about our
    systems normal operation, incidents that may happen and their resolution.
  systems:
    - name: ADK Bank Website
      description: Our company public facing website
      link: https://www.adirondackbank.com/
    - name: Helpdesk
      description: Our company support site
      link: https://support.example.com/
  dateFormat: January 2, 2006 at 3:04 PM
  disqusShortname: null
  timezoneString: " UTC"
  logo: /images/clearstatus.svg
  description_header: Information about <a class='text-grey-darkest' title='Visit
    example.com' href='https://www.example.com/'>example</a> systems operations.
  copyrightHolder: Adirondack Bank
  eventsPerPage: 10
  iconType: image/png
  icon: /images/clearstatus.png
  description_footer: <a class='text-grey-darkest' title='Visit example.com'
    href='https://www.example.com/'>Example.com</a> provides open-source
    software for all kind of sectors.
